feat: adding unit test result parsing to the build job

diff --git a/.github/workflows/Docker-CI.yml b/.github/workflows/Docker-CI.yml
--- a/.github/workflows/Docker-CI.yml
+++ b/.github/workflows/Docker-CI.yml
@@ -14,38 +14,18 @@ jobs:
 
     steps:
     - uses: actions/checkout@v3
-    # - name: Build the Docker image
-    #   run: cd source && docker build . --file Dockerfile --tag ndsp-test:$(date +%s)
-    -
-        name: Build and export
-        uses: docker/build-push-action@v2
-        with:
-          context: source
-          target: build
-          tags: ndsp-test:$(date +%s)
-          outputs: type=docker,dest=/tmp/myimage.tar
-    -
-      name: Upload artifact
-      uses: actions/upload-artifact@v2
-      with:
-        name: myimage
-        path: /tmp/myimage.tar
+    - name: Build the Docker image
+      run: cd source && docker build . --file Dockerfile --tag ndsp-test:$(date +%s)
 
-  test:
-    runs-on: ubuntu-latest
-    needs: build
-    steps:
-      -
-        name: Set up Docker Buildx
-        uses: docker/setup-buildx-action@v1
-      -
-        name: Download artifact
-        uses: actions/download-artifact@v2
-        with:
-          name: myimage
-          path: /tmp
-      -
-        name: Load image
-        run: |
-          docker load --input /tmp/myimage.tar
-          docker image ls -a
+    - name: Run Unit Tests and extract results
+      run: cd source && docker build --target export-test-results --output type=local,dest=test-results
+
+    - name: Publish Test results
+      uses: dorny/test-reporter@v1
+      if: success() || failure()    # run this step even if previous step failed
+      with:
+        name: Test Results
+        path: source/test-results/*.trx
+        reporter: dotnet-trx
+
+        
